# Generated by Django 3.0.1 on 2019-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=25)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
                ('reference', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'ptable',
            },
        ),
    ]
