# Generated by Django 3.0.1 on 2019-12-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pid',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
